version: '3'

services:
  database:
    image: mysql:5.6
    container_name: database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-net

    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    restart: always
    container_name: wordpress
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wp-net


  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - wp-data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - wp-net

networks:
  wp-net:

volumes:
  db-data:
  wp-data:  
